### ISSUE TITLE
Conflict Load .JMX File with old version JPOS Sampler when Plugin JPOS Sampler being updated

### ISSUE THREAD

**Issue by DhonyImamS** [erlanggaelfallujah/JMeter-jPOS-components#14]
Hi Erlangga,

Why I Can;t Open my JMX Project File with your last JPOS Sampler Plugin, after I Updated its Plugin with New Version ?

But when I Start from New Project, there is no problem like this

See my JMeter Log Files
----------------------------------------------------------------------------------------------------------
2016/11/03 14:00:49 INFO  - jmeter.util.JMeterUtils: Setting Locale to en_US 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: Loading user properties from: D:\Aplikasi\apache-jmeter-3.0\bin\user.properties 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: Loading system properties from: D:\Aplikasi\apache-jmeter-3.0\bin\system.properties 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: Copyright (c) 1998-2016 The Apache Software Foundation 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: Version 3.0 r1743807 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: java.version=1.8.0_101 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: java.vm.name=Java HotSpot(TM) 64-Bit Server VM 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: os.name=Windows 7 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: os.arch=amd64 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: os.version=6.1 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: file.encoding=Cp1252 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: Max memory     =1884815360 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: Available Processors =4 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: Default Locale=English (United States) 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: JMeter  Locale=English (United States) 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: JMeterHome=D:\Aplikasi\apache-jmeter-3.0 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: user.dir  =D:\Aplikasi\apache-jmeter-3.0\bin 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: PWD       =D:\Aplikasi\apache-jmeter-3.0\bin 
2016/11/03 14:00:49 INFO  - jmeter.JMeter: IP: 192.168.56.1 Name: MAMNB-0078 FullName: MAMNB-0078.kartuku.local 
2016/11/03 14:00:50 INFO  - jmeter.gui.action.LookAndFeelCommand: Using look and feel: javax.swing.plaf.metal.MetalLookAndFeel [Metal, CrossPlatform] 
2016/11/03 14:00:50 INFO  - jmeter.JMeter: Loaded icon properties from org/apache/jmeter/images/icon.properties 
2016/11/03 14:00:50 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must contain the string: '.functions.' 
2016/11/03 14:00:50 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must not contain the string: '.gui.' 
2016/11/03 14:00:54 INFO  - org.jmeterplugins.repository.PluginManager: Plugins Status: [jpgc-graphs-basic=2.0, jpgc-sense=2.3, jpgc-functions=2.0, jpgc-casutg=2.1, jpgc-dummy=0.1, jmeter-ftp=3.0, jpgc-ffw=2.0, jmeter-http=3.0, jpgc-fifo=0.2, jmeter-jdbc=3.0, jmeter-jms=3.0, jmeter-monitors=3.0, jmeter-core=3.0, jmeter-junit=3.0, jmeter-java=3.0, jmeter-ldap=3.0, jmeter-mail=3.0, jmeter-mongodb=3.0, jmeter-native=3.0, jpgc-perfmon=2.1, jpgc-plugins-manager=0.10, jmeter-tcp=3.0, jpgc-tst=2.0, jmeter-components=3.0, jpgc-standard=2.0] 
2016/11/03 14:00:56 INFO  - jmeter.util.BSFTestElement: Registering JMeter version of JavaScript engine as work-round for BSF-22 
2016/11/03 14:00:56 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:56 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:56 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:56 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:56 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser 
2016/11/03 14:00:56 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser 
2016/11/03 14:00:56 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser 
2016/11/03 14:00:56 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser 
2016/11/03 14:00:56 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
2016/11/03 14:00:56 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser 
2016/11/03 14:00:57 INFO  - jorphan.exec.KeyToolUtils: keytool found at 'keytool' 
2016/11/03 14:00:57 INFO  - jmeter.protocol.http.proxy.ProxyControl: HTTP(S) Test Script Recorder SSL Proxy will use keys that support embedded 3rd party resources in file D:\Aplikasi\apache-jmeter-3.0\bin\proxyserver.jks 
2016/11/03 14:00:57 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.mongodb.config.MongoSourceElement 
2016/11/03 14:00:57 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.mongodb.sampler.MongoScriptSampler 
2016/11/03 14:00:57 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:57 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.visualizers.DistributionGraphVisualizer 
2016/11/03 14:00:57 INFO  - jmeter.samplers.SampleResult: Note: Sample TimeStamps are START times 
2016/11/03 14:00:57 INFO  - jmeter.samplers.SampleResult: sampleresult.default.encoding is set to ISO-8859-1 
2016/11/03 14:00:57 INFO  - jmeter.samplers.SampleResult: sampleresult.useNanoTime=true 
2016/11/03 14:00:57 INFO  - jmeter.samplers.SampleResult: sampleresult.nanoThreadSleep=5000 
2016/11/03 14:00:58 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.visualizers.SplineVisualizer 
2016/11/03 14:00:58 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:58 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:58 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:58 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:58 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:00:58 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:20 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:24 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:25 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:32 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running createTestElement ... 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running modifyTestElement ,,, 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running configure ... 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running modifyTestElement ,,, 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running configure ... 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running modifyTestElement ,,, 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running configure ... 
2016/11/03 14:01:32 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running modifyTestElement ,,, 
2016/11/03 14:01:32 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running configure ... 
2016/11/03 14:01:39 INFO  - jmeter.samplers.jpos.JPOSSamplerGui: running modifyTestElement ,,, 
2016/11/03 14:01:39 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:39 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:44 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:44 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:48 INFO  - jmeter.services.FileServer: Default base='D:\Aplikasi\apache-jmeter-3.0\bin' 
2016/11/03 14:01:48 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:01:48 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:02:08 INFO  - jmeter.gui.action.Load: Loading file: D:\Project\Riset\JMeter-jPOS-components-master\JPOS Sampler.jmx 
2016/11/03 14:02:08 INFO  - jmeter.services.FileServer: Set new base='D:\Project\Riset\JMeter-jPOS-components-master' 
2016/11/03 14:02:08 INFO  - jmeter.save.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2 
2016/11/03 14:02:08 INFO  - jmeter.save.SaveService: Using SaveService properties file encoding UTF-8 
2016/11/03 14:02:08 INFO  - jmeter.save.SaveService: Using SaveService properties version 2.9 
2016/11/03 14:02:08 INFO  - jmeter.save.SaveService: All converter versions present and correct 
2016/11/03 14:02:08 INFO  - jmeter.save.SaveService: Loading file: D:\Project\Riset\JMeter-jPOS-components-master\JPOS Sampler.jmx 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 INFO  - jmeter.samplers.jpos.JPOSSampler: call constructor() ... 
2016/11/03 14:02:08 WARN  - jmeter.gui.action.Load: Unexpected error java.lang.NullPointerException
	at org.apache.jmeter.gui.custom.CustomTCPConfigGui.configure(CustomTCPConfigGui.java:107)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addComponent(JMeterTreeModel.java:146)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:121)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:121)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:121)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:113)
	at org.apache.jmeter.gui.GuiPackage.addSubTree(GuiPackage.java:492)
	at org.apache.jmeter.gui.action.Load.insertLoadedTree(Load.java:193)
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:131)
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:102)
	at org.apache.jmeter.gui.action.Load.doAction(Load.java:89)
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
	at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:40)
	at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

2016/11/03 14:02:08 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:02:08 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:02:08 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:02:20 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:02:21 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:02:23 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 
2016/11/03 14:02:24 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jpos_sampler_config] 

----------------------------------------------------------------------------------------------------------
Thanks

Dhony

**Comment by erlanggaelfallujah** [comment]
U cannot using jmx old version because variable is changed for optimizing, so not compatible with new JMeter. U must using with new JMeter.
